name: Deploy to Satisfy Host

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup SSH key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3️⃣ Deploy code to server
      - name: Deploy to Satisfy Host
        run: |
          ssh -o StrictHostKeyChecking=no yeestoc3@104.161.43.62 "
            echo '🚀 Starting deployment...'

            # Go to project directory
            cd /home/yeestoc3/testcicd || exit 1

            # Pull latest code
            echo '📥 Pulling latest code...'
            git reset --hard
            git pull origin main

            # Install dependencies
            echo '📦 Installing npm packages...'
            /usr/local/bin/npm install --production

            # Restart Passenger app (Node.js)
            echo '♻ Restarting Passenger app...'
            mkdir -p tmp
            touch tmp/restart.txt

            echo '✅ Deployment completed successfully!'
          "
