name: Deploy to Satistfy Host

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no yeestoc3@104.161.43.62 "
            cd 	/home/yeestoc3/testcicd &&
            git pull origin main &&
            npm install &&
            pm2 restart myapp || pm2 start index.js --name myapp
          "
