name: Deploy to Satistfy Host

on:
  push:
    branches:
      - main  # শুধু main branch push হলে deploy হবে

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no yeestoc3@104.161.43.62 "
            echo 'Deploying to Satistfy Host...'
            cd /home/yeestoc3/testcicd || exit 1
            echo 'Pulling latest code...'
            git pull origin main
            echo 'Installing dependencies...'
            /usr/local/bin/npm install
            echo 'Restarting app with PM2...'
            /usr/local/bin/pm2 restart testcicd || /usr/local/bin/pm2 start index.js --name testcicd -f
            echo 'Deployment completed successfully!'
          "
