name: Docker CI/CD on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy with Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_USER_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd yeestoc3/testcicd  # তোমার প্রজেক্টের সঠিক পাথ দাও
            git pull origin main
            docker-compose up -d --build --force-recreate